// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurveySystem.Infrastructure.Data;

#nullable disable

namespace SurveySystem.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SurveyDbContext))]
    [Migration("20251219003031_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SurveySystem.Domain.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("SurveySystem.Domain.Surveys.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("SurveySystem.Domain.Survey", b =>
                {
                    b.OwnsMany("SurveySystem.Domain.Question", "Questions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Order")
                                .HasColumnType("int");

                            b1.Property<Guid>("SurveyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("SurveyId");

                            b1.ToTable("Question");

                            b1.WithOwner()
                                .HasForeignKey("SurveyId");

                            b1.OwnsMany("SurveySystem.Domain.Option", "_options", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("Order")
                                        .HasColumnType("int");

                                    b2.Property<int>("QuestionText")
                                        .HasColumnType("int");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("QuestionText");

                                    b2.ToTable("Option");

                                    b2.WithOwner()
                                        .HasForeignKey("QuestionText");
                                });

                            b1.Navigation("_options");
                        });

                    b.OwnsOne("SurveySystem.Domain.SurveyPeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("SurveyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("EndDate")
                                .HasColumnType("datetimeoffset");

                            b1.Property<DateTimeOffset>("StartDate")
                                .HasColumnType("datetimeoffset");

                            b1.HasKey("SurveyId");

                            b1.ToTable("Surveys");

                            b1.WithOwner()
                                .HasForeignKey("SurveyId");
                        });

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("SurveySystem.Domain.Surveys.Submission", b =>
                {
                    b.OwnsMany("SurveySystem.Domain.Answer", "Answers", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("OptionText")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("QuestionText")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("SubmissionId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("SubmissionId");

                            b1.ToTable("Answer");

                            b1.WithOwner()
                                .HasForeignKey("SubmissionId");
                        });

                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
